name: Documentation

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install pdoc
      run: pip install pdoc3
    - name: Prepare data
      run: ./prepare.sh
    - name: Install package
      run: pip install .
    - name: Build documentation
      run: pdoc --html -o docs -f Qieyun.音韻地位
    - name: Publish
      run: |
        # Create a temporary directory
        export temp_dir=`mktemp -d -p ~`

        (
        # Preserve .git
        mv .git $temp_dir
        cd $temp_dir

        # Switch branch
        git fetch
        git checkout gh-pages
        )

        (
        # Move .git
        mv docs/Qieyun/音韻地位.html $temp_dir/index.html

        # Go to the temporary directory
        cd $temp_dir

        # Set commit identity
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        # Publish
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Publish `TZ='Asia/Hong_Kong' date`"
          git push -f origin gh-pages
        fi
        )
